### ISSUE TITLE
unhandled error for socket.close();

### ISSUE THREAD

**Issue by dregenor** [hueniverse/sntp#16]
in dgram.js module
socket.close();
can trigger error inside `_healthCheck`
```
throw new Error('Not running'); // error message from dgram_legacy.js
```
so it would be a great to wrap socket.close to try catch block

**Comment by hueniverse** [comment]
What's they scenario you are getting this thrown?

**Comment by dregenor** [comment]
sometimes when we are have unstable internet connection. (mobile internet in train for example)
socket will be closed (or not opened, i am not sure) by dgram.js
and after that will triggered `socket.once('error', (err) => finish(err));`
inside `finish` again will called socket.close()  which in this case will lead to an error.
